#!/bin/sh

green='\033[0;32m'
echo "${green}Running pre-commit updating of requirements.txt${end}"
echo "\n"

# Update requirements.txt
cd api && pip freeze > requirements.txt

# Stage the updated requirements.txt file
git add requirements.txt

# Continue with the commit
exit 0

