"""Reorganize project

Revision ID: 227e3b33bab9
Revises: 
Create Date: 2023-06-07 18:07:52.877138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '227e3b33bab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_index('flight_number')

    op.drop_table('flights')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('flight_number', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('start_destination', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('end_destination', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('takeoff_time', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('landing_time', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('flight_number'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.create_index('flight_number', ['flight_number'], unique=False)

    # ### end Alembic commands ###
