"""Add takeoff and langing time to flights db

Revision ID: 2bae1f11b31e
Revises: 
Create Date: 2023-06-06 21:07:44.846594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bae1f11b31e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('takeoff_time', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('landing_time', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['flight_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('landing_time')
        batch_op.drop_column('takeoff_time')

    # ### end Alembic commands ###
