"""add price column, change datetime format for takeoff and landing time

Revision ID: 3902dc5837e2
Revises: b93f7ce62210
Create Date: 2023-06-14 18:56:53.989416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3902dc5837e2'
down_revision = 'b93f7ce62210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Double(), nullable=False))
        batch_op.alter_column('takeoff_time',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('landing_time',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('landing_time',
               existing_type=sa.String(length=16),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('takeoff_time',
               existing_type=sa.String(length=16),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('price')

    # ### end Alembic commands ###
