name: Unit Tests

on: 
    pull_request:
        paths: ['src/api/**']

jobs:
    run_mysql:
        runs-on: ubuntu-latest
        env:
            DB_DATABASE: test_db
            DB_USER: root
            DB_PASSWORD: root
        steps:
            - name: Set up MySQL
              run: |
                sudo systemctl start mysql.service
                mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    run_tests:
        needs: run_mysql
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
                
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                cd ./src/api/ && pip install -r requirements.txt
            - name: Test with pytest
              run: |
                pytest