name: Unit Tests

on: 
    pull_request:
        types: [assigned, opened, synchronize, reopened]
        paths: ['src/api/**']

jobs:
    run_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
                
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                cd ./src/api/ && pip install -r requirements.txt
            - name: Test with pytest
              run: |
               cd ./src/api/ && pytest
